export const AllTableau: {
  name: string;
  image: string;
  width: number;
  height: number;
  price: number;
  desc: string;
  oldPrice?: any;
  start: any;
  order?: string;
  percentage?: string;
}[] = [
  {
    name: "Classic painting",
    image: "/tableau (6).jpg",
    width: 18,
    height: 30,
    price: 240,
    desc: "a classic vintage work which embellishes the environment",
    start: "",
  },
  {
    name: "Classic painting",
    image: "/tableau (7).jpg",
    width: 19,
    height: 28,
    price: 190,
    desc: "a classic work which embellishes your environment",
    start: "",
  },
  {
    name: "Original Graffiti Painting Colore",
    image: "/tableau (19).png",
    width: 28,
    height: 28,
    price: 54,
    desc: "a painting full of color Adapt to your space",
    oldPrice: "₹ 537",
    start: "",
    order: "Livraison GRATUITE",
    percentage: "(-10% de reduction)",
  },
  {
    name: "a Street Art Basket painting",
    image: "/tableau (20).png",
    width: 30,
    height: 30,
    price: 110,
    desc: "Work for people at the heart of sport, more precisely basketball",
    start: "",
  },
  {
    name: "painting Graffiti",
    image: "/tableau (8).png",
    width: 22,
    height: 22,
    price: 150,
    desc: "a classic work which embellishes your environment",
    start: "",
  },
  {
    name: "Simple Graffiti",
    image: "/tableau (2).jpg",
    width: 23,
    height: 35,
    price: 190,
    desc: "a classic work for you and your family",
    start: "",
  },
  {
    name: "Classic painting",
    image: "/tableau (11).png",
    width: 19,
    height: 34,
    price: 120,
    desc: "a classic work which embellishes your environment",
    oldPrice: "₹ 800",
    start: "",
    order: "Livraison GRATUITE",
    percentage: "(-15% de reduction)",
  },
  {
    name: "Orange elephant painting",
    image: "/tableau (7).png",
    width: 25,
    height: 37,
    price: 250,
    desc: "a classic artwork for you and your family that depicts wildlife",
    oldPrice: "₹ 900",
    start: "",
    order: "Livraison GRATUITE",
    percentage: "(-20% de reduction)",
  },
  {
    name: "painting Simple",
    image: "/tableau (1).jpg",
    width: 20,
    height: 28,
    price: 190,
    desc: "a classic painting for you and your family your living room",
    start: "",
  },
  {
    name: "painting Simple",
    image: "/tableau (5).jpg",
    width: 25,
    height: 35,
    price: 114,
    desc: "a classic painting for you and your family your living room",
    start: "",
  },
  {
    name: "Black Woman Art Nude ",
    image: "/tab(1).jpg",
    width: 23,
    height: 40,
    price: 730,
    desc: "a painting for the city which for a complete exhibition ",
    oldPrice: "₹ 900",
    start: "",
    order: "Livraison GRATUITE",
    percentage: "(-13% de reduction)",
  },
  {
    name: "painting of the Love",
    image: "/tableau (6).png",
    width: 30,
    height: 40,
    price: 175,
    desc: "this work allows you to communicate love to all people who enter your home",
    start: "",
  },
  {
    name: "painting Graffiti",
    image: "/tableau (15).png",
    width: 28,
    height: 45,
    price: 222,
    desc: "painting which represents the sea oceans and which makes life good",
    start: "",
  },
  {
    name: "painting Glamour",
    image: "/tableau (14).png",
    width: 25,
    height: 39,
    price: 250,
    desc: "painting that represents glamor and class",
    oldPrice: "₹ 1250",
    start: "",
    order: "Livraison GRATUITE",
    percentage: "(-8% de reduction)",
  },
  {
    name: "painting Graffiti",
    image: "/tableau (15).png",
    width: 28,
    height: 40,
    price: 120,
    desc: "painting which represents the sea oceans and which makes life good",
    oldPrice: "₹ 500",
    start: "",
    order: "Livraison GRATUITE",
    percentage: "(-12% de reduction)",
  },

  {
    name: "painting Graffiti",
    image: "/tableau (3).jpg",
    width: 28,
    height: 40,
    price: 120,
    desc: "painting which represents the sea oceans and which makes life good",
    start: "",
  },
  {
    name: "Colorful Street Art painting",
    image: "/tableau (4).png",
    width: 25,
    height: 40,
    price: 250,
    desc: "a Street Art Colore painting for more design in your life and those around you",
    start: "",
  },
  {
    name: "flowery painting",
    image: "/tableau (5).png",
    width: 28,
    height: 40,
    price: 200,
    desc: "flowery painting to give pollen in your room and other pierce",
    oldPrice: "₹ 500",
    start: "",
    order: "Livraison GRATUITE",
    percentage: "(-16% de reduction)",
  },
];

export const AllOreiller: {
  name: string;
  image: string;
  width: number;
  height: number;
  price: number;
  oldPrice?: number;
  start: any;
  order?: string;
  percentage?: number;
}[] = [
  {
    name: "Hatton Cushion",
    image: "/Oreiller (1).png",
    width: 17,
    height: 17,
    price: 75,
    oldPrice: 100,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Square Cushion, Grey Cover",
    image: "/Oreiller (2).png",
    width: 17,
    height: 17,
    price: 80,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Shatter Cushion Cover",
    image: "/Oreiller (3).png",
    width: 20,
    height: 20,
    price: 90,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Shatter Cushion Cover",
    image: "/Oreiller (4).png",
    width: 18,
    height: 18,
    price: 83,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Escher Cushion Cover",
    image: "/Oreiller (5).png",
    width: 20,
    height: 20,
    price: 61,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "flowery painting",
    image: "/Oreiller (6).png",
    width: 19,
    height: 19,
    price: 66,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Everson Cushion",
    image: "/Oreiller (7).png",
    width: 21,
    height: 21,
    price: 99,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Forbes Square Cushion, Grey Cover",
    image: "/Oreiller (8).png",
    width: 22,
    height: 22,
    price: 27,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Shatter Cushion Cover",
    image: "/Oreiller (9).png",
    width: 20,
    height: 20,
    price: 31,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "South Beach Cushion Cover",
    image: "/Oreiller (10).png",
    width: 19,
    height: 19,
    price: 33,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Forbes Square Cushion, Grey Cover",
    image: "/Oreiller (11).png",
    width: 17,
    height: 17,
    price: 37,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Snowshill Cushion",
    image: "/Oreiller (12).png",
    width: 15,
    height: 15,
    price: 45,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: " Cercle Cushion",
    image: "/Oreiller (13).png",
    width: 20,
    height: 20,
    price: 30,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Shatter Cushion Cover",
    image: "/Oreiller (14).png",
    width: 19,
    height: 19,
    price: 29,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Square Cushion, Grey Cover",
    image: "/Oreiller (15).png",
    width: 21,
    height: 21,
    price: 30,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Escher Cushion Cover",
    image: "/Oreiller (16).png",
    width: 18,
    height: 18,
    price: 27,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Cushion yellow grey green",
    image: "/Oreiller (17).png",
    width: 20,
    height: 20,
    price: 45,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Red Cushion",
    image: "/Oreiller (18).png",
    width: 18,
    height: 18,
    price: 22,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Hatton Cushion",
    image: "/Oreiller (19).png",
    width: 14,
    height: 14,
    price: 28,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Forbes Square Cushion, Grey Cover",
    image: "/Oreiller (20).png",
    width: 13,
    height: 13,
    price: 30,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
];

export const AllSofa: {
  name: string;
  image: string;
  width: number;
  height: number;
  price: number;
  oldPrice?: number;
  start: any;
  order?: string;
  percentage?: number;
}[] = [
  {
    name: "Hatton Cushion",
    image: "/Oreiller (1).png",
    width: 17,
    height: 17,
    price: 75,
    oldPrice: 100,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Square Cushion, Grey Cover",
    image: "/Oreiller (2).png",
    width: 17,
    height: 17,
    price: 80,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Shatter Cushion Cover",
    image: "/Oreiller (3).png",
    width: 20,
    height: 20,
    price: 90,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Shatter Cushion Cover",
    image: "/Oreiller (4).png",
    width: 18,
    height: 18,
    price: 83,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Escher Cushion Cover",
    image: "/Oreiller (5).png",
    width: 20,
    height: 20,
    price: 61,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "flowery painting",
    image: "/Oreiller (6).png",
    width: 19,
    height: 19,
    price: 66,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Everson Cushion",
    image: "/Oreiller (7).png",
    width: 21,
    height: 21,
    price: 99,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Forbes Square Cushion, Grey Cover",
    image: "/Oreiller (8).png",
    width: 22,
    height: 22,
    price: 27,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Shatter Cushion Cover",
    image: "/Oreiller (9).png",
    width: 20,
    height: 20,
    price: 31,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "South Beach Cushion Cover",
    image: "/Oreiller (10).png",
    width: 19,
    height: 19,
    price: 33,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Forbes Square Cushion, Grey Cover",
    image: "/Oreiller (11).png",
    width: 17,
    height: 17,
    price: 37,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Snowshill Cushion",
    image: "/Oreiller (12).png",
    width: 15,
    height: 15,
    price: 45,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: " Cercle Cushion",
    image: "/Oreiller (13).png",
    width: 20,
    height: 20,
    price: 30,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Shatter Cushion Cover",
    image: "/Oreiller (14).png",
    width: 19,
    height: 19,
    price: 29,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Square Cushion, Grey Cover",
    image: "/Oreiller (15).png",
    width: 21,
    height: 21,
    price: 30,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Escher Cushion Cover",
    image: "/Oreiller (16).png",
    width: 18,
    height: 18,
    price: 27,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Cushion yellow grey green",
    image: "/Oreiller (17).png",
    width: 20,
    height: 20,
    price: 45,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Red Cushion",
    image: "/Oreiller (18).png",
    width: 18,
    height: 18,
    price: 22,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Hatton Cushion",
    image: "/Oreiller (19).png",
    width: 14,
    height: 14,
    price: 28,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
  {
    name: "Forbes Square Cushion, Grey Cover",
    image: "/Oreiller (20).png",
    width: 13,
    height: 13,
    price: 30,
    oldPrice: 500,
    start: "",
    order: "Livraison GRATUITE",
    percentage: -16,
  },
];
